# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Elara Aerospace"
email: team@elara-aerospace.com
description: "We are a rocket student club in Munich from HM, TUM and Munich Business School. Our goal: breaking records, being the first student led group to shoot a Methalox rocket above 100km to space. Join Elara Aerospace, a team of diverse students pioneering the first student methalox rocket to reach 100km. Be part of our mission to redefine the limits of aerospace! 🚀"
author: "Suriyaa Sundararuban"
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://elara-aerospace.com" # the base hostname & protocol for your site, e.g. http://example.com
domain: elara-aerospace.com       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
linkedin_username: "elara-aerospace"
github_username: "elara-aerospace"
twitter_username: "Elara_Aerospace"
instagram_username: "elara_aerospace"
youtube_username: "@Elara-Aerospace"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

# Sitemap configuration
sitemap:
  exclude:
    - /404.html
    - /about.html
    - /pitch-deck.html
    - /apply.html
    - /pitch/
    - /apply/
    - /assets/pdfs/
    - /assets/slides/
    - /assets/images/
    - /assets/css/
    - /assets/js/
    - /assets/fonts/
    - /assets/favicon/
    - /COMPONENTS.html
    - /LFS_BUDGET_SOLUTION.html
    - /SECURITY.html
    - /CODE_OF_CONDUCT.md
    - /CONTRIBUTING.md
    - /LICENSE.md
    - /README.md
    - /Rakefile
    - /appveyor.yml
    - /requirements.txt
    - /Gemfile
    - /Gemfile.lock
  priorities:
    - /: 1.0
    - /about/: 0.9
    - /mission/: 0.9
    - /technology/: 0.8
    - /team/: 0.8
    - /partners/: 0.7
    - /news/: 0.7
    - /press/: 0.6
    - /contact/: 0.5
    - /inspiration/: 0.5
    - /project/: 0.4
    - /experiments/: 0.4
    - /policy/: 0.3
    - /imprint/: 0.3
  changefreq:
    - /: weekly
    - /about/: monthly
    - /mission/: monthly
    - /technology/: monthly
    - /team/: monthly
    - /partners/: monthly
    - /news/: weekly
    - /press/: monthly
    - /contact/: monthly
    - /inspiration/: monthly
    - /project/: monthly
    - /experiments/: monthly
    - /policy/: yearly
    - /imprint/: yearly

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
