# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Elara Aerospace"
email: team@elara-aerospace.com
description: "Join us on a historic journey: Be part of the first student methalox rocket to reach the Kármán line."
author: "Suriyaa Sundararuban"
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://elara-aerospace.com" # the base hostname & protocol for your site, e.g. http://example.com
domain: elara-aerospace.com       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
linkedin_username: "elara-aerospace"
github_username: "elara-aerospace"
twitter_username: "Ignition_Space"
instagram_username: "elara_aerospace"
youtube_username: "@Elara-Aerospace"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
